version: '3.8'

services:
  # 1. Serveur Web & Back-End PHP
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arcadia_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - mongodb
    networks:
      - arcadia_network

  # 2. Base de Données Relationnelle (MySQL)
  db:
    image: mysql:8.0
    container_name: arcadia_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: arcadia_zoo
      MYSQL_USER: arcadia_user
      MYSQL_PASSWORD: arcadia_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Automatisme : Exécute schema.sql au tout premier lancement de MySQL !
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    networks:
      - arcadia_network

  # 3. Base de Données NoSQL (MongoDB - Stats US 11)
  mongodb:
    image: mongo:6.0
    container_name: arcadia_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - arcadia_network

networks:
  arcadia_network:
    driver: bridge

volumes:
  db_data:
  mongo_data: