services:
  db:
    image: mariadb:10.11
    container_name: zoo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zoo_arcadia
      MYSQL_USER: zoo_user
      MYSQL_PASSWORD: zoo_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  web:
    build: .
    container_name: zoo_web
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

volumes:
  db_data: